#!/usr/bin/env python3
"""Build the MCQ data and inject it into mcq_trainer.html.

Authoring rules (from study_sheets_recipe v1):
  * Situational / application focus, not rote definitions ("which framework
    would you use if…", "this case is an example of…", "the diagnosis is…").
  * 30 questions per block.
  * All four options ≈ the same length (longer ≠ correct).
  * Distractors swap close (neighbouring) concepts or authors.
  * Single best answer; rationale names the trap.

Workflow:
    $ python3 _build_mcq.py
        - audits option-length parity (flags any answer that's noticeably
          longer than its longest distractor)
        - writes the JSON into mcq_trainer.html in place
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HTML = ROOT / "mcq_trainer.html"

# Length-parity tolerance: correct option may be at most this many characters
# longer than the LONGEST distractor. Below the threshold we let it pass.
LENGTH_TOLERANCE = 10

# ---------------------------------------------------------------------------
# Question bank — 6 blocks × 30 questions
# Each question: (stem, [4 options], correct_index, rationale)
# ---------------------------------------------------------------------------

def Q(stem, options, answer, rationale):
    return {"q": stem, "options": options, "answer": answer, "rationale": rationale}


BLOCK_1 = [
    Q("Ryanair is criticized for treating staff as a pure cost item. A consultant argues the firm should redesign HR around stakeholders, not only shareholders. Which model best supports the argument?",
      ["Michigan Model", "Harvard Model", "Pay Model", "AMO Model"], 1,
      "Harvard = multistakeholder, normative, Four C's. Michigan is the shareholder/matching contrast."),
    Q("A capable, motivated employee underperforms because the role lacks tools, authority and information. The model that predicts this failure is:",
      ["Ability–Motivation–Opportunity", "Three-Component Commitment", "Self-Determination Theory", "Conservation of Resources"], 0,
      "AMO is multiplicative — zero Opportunity zeros performance, regardless of Ability and Motivation."),
    Q("An engineer stays only because she would lose her stock vesting if she left. Per Meyer & Allen this is:",
      ["Affective commitment", "Normative commitment", "Continuance commitment", "Behavioral commitment"], 2,
      "Continuance = 'cost of leaving'. The worst commitment type for performance and well-being."),
    Q("A survey shows staff are full of energy, deeply involved, and lose track of time at work. Per Schaufeli & Bakker this measures:",
      ["Job satisfaction", "Work engagement", "Affective commitment", "Intrinsic motivation"], 1,
      "Vigor + Dedication + Absorption = work engagement (VDA)."),
    Q("A firm adds Play, Purpose and Potential to daily work and removes economic pressure. Which framework is being applied?",
      ["AMO Model", "Total Motivation (ToMo)", "DREAMS framework", "Job Characteristics Model"], 1,
      "ToMo's direct motives are Play / Purpose / Potential; indirect are emotional / economic pressure and inertia."),
    Q("A salesperson lies to a customer to protect the firm's quarterly numbers. The literature calls this:",
      ["Counterproductive Work Behavior", "Unethical Pro-Organizational Behavior", "Organizational Citizenship Behavior", "Workplace Deviance"], 1,
      "UPB = unethical acts FOR the firm. The dark side of strong commitment / engagement."),
    Q("A HR director adopts a tight matching model: strategy → HR cycle (selection, appraisal, rewards, development) with shareholder returns as the test. This is closest to:",
      ["Harvard Model", "Michigan Model", "Strategic Fitness Process", "Resource-Based View"], 1,
      "Michigan = matching, four-stage HR cycle, shareholder-oriented."),
    Q("An engagement survey shows high Vigor but low Dedication and Absorption. The best framing of this gap is:",
      ["Energy without meaning — partial engagement", "Continuance commitment trap dynamics", "AMO failure on the Opportunity side", "Onset of organizational burnout"], 0,
      "Engagement requires all three of Vigor, Dedication, Absorption — high V alone leaves people running on empty."),
    Q("A new policy lets staff propose strategy changes through a structured truth-to-power session. This is an example of:",
      ["360-degree feedback", "Strategic Fitness Process", "Management by Objectives", "Organizational Citizenship Behavior"], 1,
      "Beer & Eisenstat's SFP — surfaces strategy/values misalignment hidden by hierarchy."),
    Q("Beer, Boselie & Brewster's central critique of dominant HRM research is that it:",
      ["Ignores organizational culture entirely", "Focuses narrowly on shareholder outcomes", "Underestimates personality and traits", "Overstates the political role of unions"], 1,
      "Their thesis: HRM must serve a wide stakeholder set, not just shareholders."),
    Q("A firm implements practices that satisfy autonomy, competence and relatedness. The theory that predicts intrinsic motivation rising is:",
      ["Conservation of Resources", "Self-Determination Theory", "Social Exchange Theory", "Expectancy Theory"], 1,
      "SDT (Deci & Ryan) — three basic psychological needs."),
    Q("Staff trust their manager to deliver on promises, so they reciprocate with extra effort. The best theoretical lens is:",
      ["Social Exchange Theory", "Self-Determination Theory", "Job Characteristics Model", "Two-Factor Theory"], 0,
      "SET (Cropanzano & Mitchell) — reciprocal obligations and benefits drive discretionary effort."),
    Q("A burnout-prevention strategy assumes supportive practices help employees gain and protect resources, creating an upward spiral. The underlying theory is:",
      ["Self-Determination Theory", "Social Exchange Theory", "Conservation of Resources", "Job Demands–Resources"], 2,
      "COR (Hobfoll) — gain and loss spirals around valued resources."),
    Q("A study finds recognition, justice and psychological safety boost engagement. The mediating construct is:",
      ["Affective commitment", "Perceived Organizational Support", "Total Motivation score", "Self-efficacy"], 1,
      "POS — perception that the firm cares; the listed antecedents are POS drivers."),
    Q("A pharma firm tells employees 'you can be yourself, bad news is shared, strengths are magnified'. The framework being applied is:",
      ["DREAMS / Best Workplace on Earth", "Strategic Fitness Process", "Three-Component Commitment", "Total Motivation"], 0,
      "DREAMS — Differences, Radical honesty, Extra value, Authenticity, Meaning, Simple rules (Goffee & Jones)."),
    Q("HRM defined as 'the design of activities that affect employee behavior to implement strategic needs' emphasizes:",
      ["Strategic HRM with vertical and horizontal fit", "Pure resource-based view of human capital", "The Harvard model's stakeholder logic", "ToMo's motivational logic"], 0,
      "SHRM = behavior design serving strategy, requiring vertical (strategy) AND horizontal (within-HR) fit."),
    Q("Two HR bundles contradict each other (teamwork training paired with individual ranking). The problem is:",
      ["Vertical fit problem", "Horizontal fit problem", "Strategic decoupling", "Stakeholder misalignment"], 1,
      "Horizontal fit = HR practices reinforce each other. Vertical fit = HR matches strategy."),
    Q("A consultant says 'employees are valuable, rare, hard to imitate — a source of sustained advantage'. This is most aligned with:",
      ["Harvard Model", "Resource-Based View", "Conservation of Resources", "Stakeholder Theory"], 1,
      "RBV / human capital — people as VRIO competitive advantage."),
    Q("An engaged-but-overcommitted team starts cutting corners to 'protect the brand'. The framework that warns about this is:",
      ["AMO Model", "Unethical Pro-Organizational Behavior", "Perceived Organizational Support", "DREAMS framework"], 1,
      "UPB literature flags this exact dark-side failure mode of strong commitment."),
    Q("An employee says 'I'd feel guilty leaving — the firm invested in me'. Per Meyer & Allen this is:",
      ["Affective commitment", "Continuance commitment", "Normative commitment", "Calculative commitment"], 2,
      "Normative = sense of obligation / loyalty."),
    Q("Harvard's 'Four Cs' are best described as:",
      ["Inputs into the HRM model design", "Mid-level HR outcomes of the model", "Stakeholder categories in the model", "Strategic-fit dimensions of the model"], 1,
      "Commitment, Competence, Congruence, Cost-effectiveness — middle-layer HR outcomes."),
    Q("An employee performs brilliantly with autonomy but withers under tight monitoring. Per SDT the violated need is:",
      ["Autonomy", "Competence", "Relatedness", "Achievement"], 0,
      "Heavy monitoring undermines autonomy; performance drop is exactly what SDT predicts."),
    Q("A firm shifts to fixed bonuses paid regardless of effort. ToMo predicts:",
      ["The Play motive will rise", "Purpose and Potential will rise", "Inertia rises and direct motives weaken", "There will be no measurable effect"], 2,
      "Detached pay → Inertia (indirect motive) rises; direct motives like Purpose and Play weaken."),
    Q("A startup CEO claims 'if we treat people well, we don't need unions'. The Block-6 author who challenges this is:",
      ["Beer, Boselie & Brewster", "Pfeffer", "Doshi & McGregor", "Schaufeli & Bakker"], 1,
      "Pfeffer's reading: even good HR doesn't make unions redundant; unions can sustain HPWS."),
    Q("A multistakeholder lens judges an HR redesign primarily by:",
      ["Shareholder financial returns alone", "Employee well-being as sole criterion", "Balance of economic + societal outcomes", "Compliance with regulation as priority"], 2,
      "Multistakeholder HRM (Beer, Boselie & Brewster) — multi-dimensional well-being."),
    Q("A team leader removes meaningless rules and explains the firm's true purpose. The DREAMS attributes activated are:",
      ["Differences + Authenticity", "Simple rules + Meaning", "Extra value + Radical honesty", "Authenticity + Simple rules"], 1,
      "'Stupid rules don't exist' (Simple rules) + 'firm stands for something meaningful' (Meaning)."),
    Q("Research finds affective commitment correlates more strongly with discretionary effort than continuance commitment. The implication is:",
      ["HRM should engineer continuance via golden handcuffs", "HRM should build affective commitment via meaning and support", "Normative commitment is the most useful for firms", "All three commitment types produce identical outcomes"], 1,
      "Affective is the 'good' commitment; HRM levers (meaning, justice, support) build it."),
    Q("Which is NOT one of the four HR policy areas in the Harvard Model?",
      ["Employee influence", "HR flow", "Reward systems", "External alignment"], 3,
      "The four are: employee influence, HR flow, reward systems, work systems. External alignment is a SHRM concept."),
    Q("A long-tenured employee shows low affective and high continuance commitment. The biggest risk is:",
      ["Quitting in the next quarter", "Becoming a high-performing innovator", "Disengaged presenteeism — stays but checks out", "Becoming a union steward"], 2,
      "Continuance = trapped, affective absent = no emotional pull. Classic presenteeism profile."),
    Q("A CEO replaces individual stretch goals with team-level purpose-driven metrics. ToMo predicts:",
      ["Direct motives rise; ToMo improves", "Inertia rises sharply across team", "Emotional pressure rises markedly", "Continuance commitment rises sharply"], 0,
      "Purpose is a direct motive; team-level meaning > individual pressure."),
]

BLOCK_2 = [
    Q("A consultant maps a manager's role: lots of accountability, narrow control, no support. Per Simons the diagnosis is:",
      ["Crisis of resources", "Crisis of control", "Red tape crisis", "Crisis of identity"], 0,
      "Demand (accountability) > Supply (control + support) → resources crisis."),
    Q("A role has high autonomy, ample resources, and minimal accountability metrics. Per Simons this is a:",
      ["Crisis of resources", "Crisis of control", "Crisis of stretch", "Red tape crisis"], 1,
      "Supply > Demand → control problem: no measurement, no alignment lever."),
    Q("To widen an analyst's span of influence Simons recommends:",
      ["Increase autonomy and decision rights", "Add stretch goals plus cross-unit demands", "Add more direct reports to the role", "Centralize decision rights at the top"], 1,
      "Stretch goals + cross-unit demands push the employee to reach beyond unit boundaries."),
    Q("A dull assembly job is redesigned with task variety, identity, significance, autonomy and feedback. Hackman & Oldham predict:",
      ["Drop in internal pay equity scores", "Higher MPS score and stronger motivation", "Higher continuance commitment levels", "Reduced span of accountability metrics"], 1,
      "Five core characteristics → critical psychological states → motivation and satisfaction."),
    Q("An MPS calculation shows high Variety + Identity + Significance but zero Autonomy. The formula gives:",
      ["MPS high because the trio averages high", "MPS zero — Autonomy multiplies the score", "MPS undefined and unmeasurable", "Feedback fully compensates for autonomy"], 1,
      "MPS = ((V+I+S)/3) × Autonomy × Feedback. Zero on Autonomy OR Feedback zeros the score."),
    Q("A job description lists tasks, duties and reporting. The job specification, by contrast, lists:",
      ["Strategic objectives and goals", "KPIs and review cadence dates", "KSAOs and personal characteristics", "Pay grade and benefits package"], 2,
      "Description = the job; specification = the person."),
    Q("A growth firm forecasts demand > supply for engineers. Which is NOT a fitting response?",
      ["External recruitment", "Internal training and mobility", "Retention bonuses", "Hiring freeze"], 3,
      "A hiring freeze tackles demand < supply (oversupply), not a shortage."),
    Q("A telecoms firm faces demand < supply after automation. The most appropriate response is:",
      ["Aggressive external recruitment", "Voluntary exits and redeployment", "Stretch sales targets", "Job rotation programs"], 1,
      "Oversupply → close the gap by reducing or redeploying the workforce."),
    Q("A vacancy is filled by promoting an internal candidate. The biggest trade-off is:",
      ["Higher cost than external hires", "Less performance data available", "Creates a downstream vacancy", "Loss of cultural fit"], 2,
      "Internal recruitment is cheap and culturally aligned, but it leaves a new gap behind."),
    Q("A startup wants fresh ideas and unique skills. The right recruitment source is:",
      ["Internal job postings exclusively", "Employee referrals as sole channel", "External channels — ads and agencies", "Internal promotion as sole channel"], 2,
      "External = fresh skills and ideas — though costlier and less performance data."),
    Q("A six-step selection process (Armstrong) ends with:",
      ["Reference checks", "Job offer", "Selection test", "Application form"], 1,
      "Application → tests → interviews → references → physical → offer."),
    Q("A hiring panel asks 'Tell me about a time you handled an upset client'. This is a:",
      ["Situational question", "Behavioral question", "Stress test", "Brain teaser"], 1,
      "Past behavior = behavioral. 'What would you do if…' = situational."),
    Q("A graduate recruiter asks 'What would you do if a teammate missed a deadline?'. This is a:",
      ["Behavioral question", "Situational question", "Personality probe", "Reference question"], 1,
      "Hypothetical → situational. Suited to inexperienced candidates (Latham & Sue-Chan)."),
    Q("STAR's 'Action' step is most informative when the candidate uses:",
      ["'We' statements to show team spirit", "'I' statements describing personal actions", "Industry jargon to show expertise", "Long lists of all actions taken"], 1,
      "STAR reveals individual behavior; 'we' answers hide the candidate."),
    Q("An interviewer rates a candidate harshly because the previous one was outstanding. This is the:",
      ["Halo effect", "Similar-to-me effect", "Contrast effect", "Central tendency error"], 2,
      "Contrast = judging relative to others recently interviewed."),
    Q("A workforce planning model is best described as balancing:",
      ["Internal vs external candidates", "Labor demand vs labor supply", "Pay equity vs total cost", "Selection vs socialization"], 1,
      "Demand vs supply — right person, right job, right time, right cost."),
    Q("A team manager wants to add variety, cross-functional exposure and challenge to a junior role. The right Block-2 lever is:",
      ["Job rotation + enrichment", "Layoff via skill criteria", "Forced distribution rating", "ToMo motivation design"], 0,
      "Rotation = cross-functional movement; enrichment = added challenge and autonomy."),
    Q("Adding tasks at the SAME level of responsibility is:",
      ["Job enrichment", "Job enlargement", "Job rotation", "Job stretching"], 1,
      "Enlargement = horizontal task variety; enrichment = vertical (more autonomy)."),
    Q("A RACI matrix lists two people as 'Accountable'. The rule violated is:",
      ["Each task needs a Responsible role", "Only one person can be Accountable", "Consulted always precedes Informed", "Informed parties must be senior"], 1,
      "Single A per task; multiple A = no ownership."),
    Q("An ad campaign portrays the firm as 'the best place to grow your career'. This is leveraging:",
      ["STAR storytelling", "Employer brand / EVP", "AMO opportunity", "Total Motivation"], 1,
      "Employer brand + EVP = positioning to attract candidates."),
    Q("A firm laying off 'last in, first out' is using:",
      ["Skill-based criteria", "Merit-based criteria", "Seniority-based criteria", "Personal-situation criteria"], 2,
      "LIFO = seniority — the longest-tenured are protected."),
    Q("A factory layoff retains only multi-skilled operators. This is:",
      ["Skill-based selection", "Merit-based selection", "Status-based selection", "Personal-situation selection"], 0,
      "Skill = keep critical capabilities; merit = pure performance ranking."),
    Q("A consultant defines a competency model with technical and leadership clusters. The KSAO framework was articulated by:",
      ["Hackman & Oldham", "Campion and colleagues", "Beer and colleagues", "Latham and Sue-Chan"], 1,
      "Campion et al. (2011) on competency modeling."),
    Q("A manager complains she can't influence what gets measured. Per Simons this is mostly a:",
      ["Span-of-control problem", "Span-of-support problem", "Span-of-accountability problem", "Span-of-influence problem"], 2,
      "Accountability = range of metrics; she doesn't shape what's measured."),
    Q("A new role gives a manager a stretch goal she can't achieve alone. Simons predicts:",
      ["Reduced span of accountability", "Widened span of influence", "Increased span of control", "Eliminated need for support"], 1,
      "Stretch goals + cross-unit demands push managers to seek cross-boundary cooperation."),
    Q("A panel interview using the same competency-anchored questions for every candidate is:",
      ["Unstructured interview", "Semi-structured interview", "Structured interview", "Stress interview"], 2,
      "Same questions + rubric across candidates = structured (highest validity)."),
    Q("A study finds unstructured interviews and college GPA predict performance poorly. The author most associated is:",
      ["Aguinis", "Cappelli", "Beer", "Pfeffer"], 1,
      "Cappelli (2019) — the classic Block 3 reading on weak predictors."),
    Q("A retail chain is told supply of cashiers exceeds demand. Best initial step:",
      ["Hire externally to match demand", "Analyze workforce + forecast gap", "Issue immediate mass layoffs", "Cut existing cashier wages"], 1,
      "Workforce planning starts with analysis BEFORE acting."),
    Q("A senior role has wide influence but narrow accountability. Long term the risk is:",
      ["Burnout from over-measurement", "Drift — no metric anchors the role", "Layoffs of subordinates", "External recruitment crisis"], 1,
      "Without accountability, influence is unfocused and unmeasured."),
    Q("When a job's spans don't form an 'X' (supply ≠ demand), Simons recommends:",
      ["Accept it — perfect fit is rare", "Adjust the slider until the X is restored", "Fire the role-holder", "Switch to a Michigan-style HR cycle"], 1,
      "Redesign the job by adjusting the misaligned span."),
]

BLOCK_3 = [
    Q("A new training program shows great satisfaction surveys but no on-the-job behavior change. Kirkpatrick says you've measured:",
      ["Levels 1-2 but not 3-4", "Levels 3-4 but not 1-2", "Level 4 (Results) only", "Level 3 (Behavior) only"], 0,
      "Reactions + Learning measured; Behavior + Results not."),
    Q("A trainer skips needs assessment and jumps straight to design. The Training Process Model warns:",
      ["Higher reactions scores will follow", "Design will solve the wrong gap", "Validity will automatically rise", "Turnover will drop noticeably"], 1,
      "Without needs assessment, design solves a phantom problem."),
    Q("A candidate uses STAR but says 'we set up the process, we did the demo, we closed the deal'. The interviewer should be concerned because:",
      ["The candidate is being too collaborative", "STAR's Action needs personal 'I' detail", "STAR shouldn't include teamwork at all", "STAR doesn't require results to be cited"], 1,
      "'We' answers obscure the individual contribution — the whole point of STAR."),
    Q("A firm hires for culture fit and reuses interviewers from one department. Over years the firm becomes homogeneous. The diagnosis is:",
      ["Over-selection for Person–Organization fit", "Over-selection for Person–Job fit", "Failed socialization process", "Validity-and-reliability collapse"], 0,
      "Over-weighting P-O fit reduces diversity and innovation."),
    Q("A specialist with strong skills but weak cultural alignment can be:",
      ["Easily socialized into the culture", "Easily retrained on technical skills", "Replaced via internal mobility", "Diagnosed via the JCM model"], 0,
      "P-O fit (culture) can be socialized; P-J fit (skills) is harder to retrain."),
    Q("Per Judge et al. (2007) the strongest SINGLE predictor of job performance overall is:",
      ["Conscientiousness trait", "General mental ability", "Years of job experience", "Self-efficacy measure"], 1,
      "GMA is the single strongest; among personality, conscientiousness leads."),
    Q("An assessment battery includes a Big Five test + a cognitive ability test + a structured interview. The combo is justified by:",
      ["Aguinis' PM cycle", "Judge et al.'s predictor model", "Simons' Four Spans of Job Design", "Beer's Harvard HRM model"], 1,
      "Judge et al. show GMA + conscientiousness + experience drive validity."),
    Q("Spencer Stuart's culture framework plots culture on two axes. These are:",
      ["Cost × Quality dimensions", "Independence × Flexibility–Stability", "Centralization × Specialization", "Speed × Safety dimensions"], 1,
      "Independence–Interdependence × Flexibility–Stability → 8 culture styles."),
    Q("A new hire is trained on company values, then on team norms, then on the role. This sequences:",
      ["Strategy → Structure → Systems", "Organization → Group → Task", "Vision → Mission → Values", "Selection → Onboarding → Dev"], 1,
      "Three domains of socialization."),
    Q("All new analysts start the same 4-week orientation cohort. This is:",
      ["Sequential socialization", "Individual socialization", "Collective socialization", "Just-in-time onboarding"], 2,
      "Cohort group training at start = collective."),
    Q("A test gives identical scores across raters but doesn't predict performance. It is:",
      ["Valid but not reliable", "Reliable but not valid", "Both valid and reliable", "Neither valid nor reliable"], 1,
      "Consistency = reliable; doesn't predict outcome = not valid."),
    Q("A firm rebrands as 'the place that grows your career'. This is an example of:",
      ["Employer Value Proposition", "Performance Management", "Behavioral interview style", "Training-needs assessment"], 0,
      "EVP = what employees get in return; pairs with employer brand."),
    Q("A learning program teaching the skills needed for the CURRENT job is:",
      ["Development", "Training", "Socialization", "Workforce planning"], 1,
      "Training = current role; development = future roles."),
    Q("A leadership pipeline preparing managers for VP roles five years out is:",
      ["Training", "Development", "Onboarding", "Performance appraisal"], 1,
      "Future-oriented preparation = development."),
    Q("A consultant argues all unstructured interviews should be replaced. The stance is best supported by:",
      ["Aguinis", "Cappelli", "Hackman & Oldham", "Hobfoll"], 1,
      "Cappelli (2019): unstructured interviews and grades are weak predictors."),
    Q("A three-interviewer panel scores candidates with a shared rubric on identical questions. This is:",
      ["Unstructured interview style", "Semi-structured interview style", "Fully structured interview", "360-degree feedback method"], 2,
      "Same questions + rubric + multiple raters = fully structured (highest validity)."),
    Q("A startup chooses internal referrals over external ads. The likely trade-off is:",
      ["Substantially higher cost per hire", "Less initial cultural alignment", "Possible drop in diversity and fresh skills", "Worse retention rates over time"], 2,
      "Internal/referral channels lean toward familiar profiles; diversity is a risk."),
    Q("An onboarding program pairs each new hire with one assigned mentor for six months. This uses:",
      ["Sequential socialization", "Individual socialization", "Collective socialization", "Anticipatory socialization"], 1,
      "1-on-1 long-term mentorship = individual."),
    Q("An onboarding plan progresses through fixed weekly stages on a predetermined timetable. This uses:",
      ["Sequential socialization", "Individual socialization", "Collective socialization", "Continuous socialization"], 0,
      "Predetermined stages + timing = sequential."),
    Q("An HR director skips Phase 1 of the Fisher / Schoenfeldt / Shaw selection model. She has neglected:",
      ["Decision-making completeness", "Measurement of techniques", "Process evaluation by the org", "Candidate experience design"], 1,
      "Phase 1 = Measurement; Phase 2 = Decision; Phase 3 = Evaluation."),
    Q("A culture analysis scores high on Results + Authority + Order. Spencer Stuart's axes locate this as:",
      ["Independent + Stable quadrant", "Interdependent + Flexible", "Interdependent + Stable", "Independent + Flexible"], 0,
      "Results / Authority / Order cluster in the independent + stable quadrant."),
    Q("A training program is judged by ROI: cost vs measurable revenue uplift. This is Kirkpatrick:",
      ["Level 1 (Reactions)", "Level 2 (Learning)", "Level 3 (Behavior)", "Level 4 (Results)"], 3,
      "Level 4 = business results / ROI."),
    Q("A consulting firm with high P-O selection later struggles with groupthink. The literature's fix is:",
      ["Increase P-J fit weighting and seek complementary candidates", "Increase P-O fit weighting and tighten culture filter", "Adopt Big Five testing as the sole criterion", "Eliminate structured interviews from the process"], 0,
      "Diversify by weighting P-J fit and complementary KSAOs."),
    Q("A behavioral question is best answered via STAR. The 'R' should ideally be:",
      ["A statement of personal intent", "A measurable, attributable outcome", "A general reflection on the past", "A team-wide claim of success"], 1,
      "Result = quantifiable outcome + what was learned."),
    Q("A new graduate has no work history. The interview style most suited to them is:",
      ["Behavioral interview", "Situational interview", "Unstructured interview", "Stress interview"], 1,
      "Without past behavior, situational hypotheticals tap intentions and cognitive ability."),
    Q("A senior hire with 15 years of experience is better assessed via:",
      ["Behavioral interview", "Situational interview", "Personality test only", "Brain-teaser interview"], 0,
      "Past behavior is a stronger predictor whenever it exists."),
    Q("A selection scheme over-favors candidates similar to existing employees. The result is:",
      ["Selection contamination", "Validity decay over time", "Reduced diversity / homogenization", "Halo error in ratings"], 2,
      "Similar-to-me bias accumulated → homogeneous workforce."),
    Q("Training a new manager on the org's mission, values and history covers which domain?",
      ["Organization socialization", "Group / department socialization", "Task socialization", "Strategic socialization"], 0,
      "Mission / values / history = organization-level socialization."),
    Q("A common pitfall in onboarding is skipping the task-level introduction. New hires lack:",
      ["Cultural awareness of the firm", "Role clarity and resource access", "Peer-network relationships", "Strategic understanding of vision"], 1,
      "Task socialization = responsibilities, performance expectations, tools."),
    Q("Armstrong's recruitment & selection arc starts with:",
      ["Sourcing candidates externally", "Defining requirements (role + person)", "Conducting structured interviews", "Sending out the job offers"], 1,
      "Define requirements first; everything else flows from that."),
]

BLOCK_4 = [
    Q("A firm replaces annual appraisals with monthly check-ins and forward-looking statements. This is closest to:",
      ["Aguinis' 'appraisal' pole", "Aguinis' 'management' pole", "Forced-distribution rating", "360-degree feedback"], 1,
      "Continuous + future-focused + manager-owned = management end of the dial."),
    Q("A bank's annual rating system inflates everyone to 'exceeds expectations'. The most direct fix is:",
      ["Add 360-degree feedback", "Switch to forced distribution", "Drop ratings entirely", "Add many more KPIs"], 1,
      "Forced distribution breaks inflation by requiring differentiation."),
    Q("A high-talent team is forced to label one star as 'low achiever'. This is a known cost of:",
      ["Absolute rating systems", "BARS scoring scales", "Forced-distribution ranking", "MBO goal-attainment scoring"], 2,
      "Forced distribution can be unfair when the entire team is strong."),
    Q("Vitality Health replaced 13 absolute levels with five relative categories. The labels were:",
      ["A, B, C, D, F", "Top / Achiever / Low / Unacceptable / NR", "Outstanding / Strong / Solid / Weak / Failing", "5 / 4 / 3 / 2 / 1"], 1,
      "T / A / L / U / NR — case-specific labels (Bingham & Beer)."),
    Q("A 360 program rolls out in a low-trust unit and ratings are tied to bonus decisions. Aguinis predicts:",
      ["Honest, calibrated peer feedback", "Inflated or strategic political ratings", "Reduction of all rater errors", "Higher psychological safety"], 1,
      "360 needs psychological safety + dev-only use; otherwise it gets gamed."),
    Q("A sales appraisal anchors numeric scores with specific behaviors from critical incidents. This is:",
      ["Management by Objectives", "Behaviorally Anchored Rating Scale", "Behavioral Observation Scale", "Mixed Standard Scale"], 1,
      "BARS = numeric levels anchored by behavioral examples."),
    Q("A leader sets specific, measurable, attainable, relevant, time-bound goals with each employee. This is:",
      ["MBO supported by SMART goals", "Behaviorally anchored rating", "Forced-distribution ranking", "360-degree feedback"], 0,
      "MBO operationalized with SMART goal criteria."),
    Q("A rater consistently clusters everyone in the middle of the scale. This is:",
      ["Halo error", "Leniency error", "Central tendency error", "Recency bias error"], 2,
      "Central tendency = 'play it safe in the middle'."),
    Q("A KPI captures variance unrelated to the job's actual performance. The measure is:",
      ["Deficient", "Contaminated", "Reliable", "Relevant"], 1,
      "Contaminated = irrelevant variance creeps in. Deficient = missing relevant content."),
    Q("A KPI fails to capture an important aspect of the job. The measure is:",
      ["Deficient", "Contaminated", "Unreliable", "Invalid"], 0,
      "Deficient = missing relevant content."),
    Q("Aguinis' Performance Management cycle is built on which three pillars?",
      ["Plan / Do / Review", "Identify / Measure / Develop", "Recruit / Train / Retain", "Goal / Appraise / Reward"], 1,
      "PM = identifying (what) → measuring (how) → developing — aligned to strategy."),
    Q("Deloitte's reinvented PM replaced ratings with weekly check-ins and four future-focused statements such as:",
      ["I would always want this person on my team", "This person earned an A+ rating this year", "This person should be ranked first overall", "This person needs a performance improvement plan"], 0,
      "One of Deloitte's four practitioner statements (HBR)."),
    Q("A manager gives an SBI-Next feedback. The 'I' stands for:",
      ["Intent", "Impact", "Instruction", "Inspiration"], 1,
      "Situation – Behavior – Impact – Next step."),
    Q("A reviewer rates an employee high on every dimension because of one impressive strength. This is:",
      ["Halo error", "Leniency error", "Recency bias", "Similar-to-me bias"], 0,
      "Halo = one trait colors all ratings."),
    Q("An appraisal weighted toward enduring personality traits (vs behaviors or outcomes) is risky because:",
      ["Traits tend to be highly measurable", "Traits are hard to change and bias-prone", "Trait-based rating is the only valid format", "Aguinis explicitly recommends traits-only"], 1,
      "Trait-based ratings can drift into bias and don't link directly to action."),
    Q("A retailer scores each employee on the frequency of specific effective behaviors. This is:",
      ["Mixed Standard Scale", "Behaviorally Anchored Rating", "Behavioral Observation Scale", "Forced-distribution ranking"], 2,
      "BOS = frequency ratings on specific effective behaviors."),
    Q("Frame-of-reference training is mainly used to reduce:",
      ["Halo / leniency / contrast errors", "Test–retest reliability issues", "Validity coefficient noise", "Job-analysis sampling error"], 0,
      "FOR training calibrates raters and curbs systematic errors."),
    Q("A PM redesign aligns evaluation cycles to a common January date so everyone is rated together. This is:",
      ["A common-cycle reform (Vitality Health)", "A 360-degree feedback redesign", "A BARS introduction across roles", "A SMART-goal-only overhaul"], 0,
      "Vitality's January-cycle reform is a common-cycle move."),
    Q("A leadership style on Blake & Mouton's grid scoring 9 on people AND 9 on task is:",
      ["Authority-compliance (9,1)", "Country club (1,9)", "Team management (9,9)", "Impoverished (1,1)"], 2,
      "9,9 = team management — high on both."),
    Q("A manager's appraisal asks 'what proportion of objectives did the employee meet?'. This is:",
      ["Management by Objectives", "Behaviorally Anchored Rating", "Forced-distribution ranking", "360-degree feedback"], 0,
      "MBO is goal-attainment based."),
    Q("A rater is unduly influenced by recent events in the appraisal window. This is:",
      ["Recency bias", "Halo bias", "Contrast bias", "Central tendency bias"], 0,
      "Recency = the last few months dominate."),
    Q("A small team of 4 makes simple ranking impractical. The best alternative comparative method is:",
      ["Forced distribution", "BARS scoring scale", "Paired comparison", "Absolute rating scale"], 2,
      "Paired comparison works well at small N; forced distribution makes no sense at N=4."),
    Q("A measure passes the Relevance Venn check only when it is:",
      ["Reliable, valid, free of contamination", "Reliable only across raters and times", "Free of bias and contamination only", "Free of central-tendency drift only"], 0,
      "Relevance Venn requires all: relevant, reliable, valid + not deficient + not contaminated."),
    Q("Aguinis et al. (2011) argue most PM systems fail because they:",
      ["Do appraisal but call it management", "Use too few KPIs in the rating", "Don't tie ratings to bonus pay", "Lack 360-degree feedback inputs"], 0,
      "Central 'Why we hate PM' thesis."),
    Q("A peer leaves a low-trust 360 review on a colleague during a layoff round. The likely outcome is:",
      ["Honest and well-calibrated feedback", "Strategic or politically inflated feedback", "Sharp reduction of halo error effects", "Higher reliability of BARS ratings"], 1,
      "360 in low-trust + stakes-tied contexts gets political."),
    Q("SMART goals are most useful when:",
      ["Setting team culture norms", "Managing low performers under a PIP", "Designing 360-degree instruments", "Calibrating BARS scoring rubrics"], 1,
      "SMART operationalizes goals; key for performance improvement plans."),
    Q("A relative-ranking system always implies:",
      ["Comparison among employees", "Fixed numerical standards", "360-degree feedback input", "Behaviorally anchored scales"], 0,
      "Relative = vs other employees, not vs fixed criteria."),
    Q("A manager wants more behavior-anchored appraisals without the cost of BARS. A lighter alternative is:",
      ["BOS — rate frequency of behaviors", "Forced-distribution ranking", "Management by Objectives", "360-degree feedback only"], 0,
      "BOS is cheaper than BARS and still behavior-focused."),
    Q("Aguinis defines PM's underlying performance logic with the formula:",
      ["P = A + M + O (additive)", "P = A × M × O (MOA logic)", "P = Goals × Feedback intensity", "P = Behavior × Outcome score"], 1,
      "PM rests on Motivation × Opportunity × Ability."),
    Q("A PM cycle aligned to strategy but disconnected from compensation risks:",
      ["Becoming purely administrative", "Losing motivational and behavioral pull", "Maximizing horizontal HR fit", "Increasing rater error rates"], 1,
      "PM not linked to reward loses behavioral traction over time."),
]

BLOCK_5 = [
    Q("A firm's pay system is internally fair and externally competitive but has no link to performance. Per the Four Criteria it's missing:",
      ["Internal equity criterion", "External equity criterion", "Performance-link criterion", "Cost-benefit criterion"], 2,
      "Four Criteria = internal equity + external equity + performance link + cost/benefit."),
    Q("A salary survey is the main tool for:",
      ["Internal equity assessment", "External equity benchmarking", "Performance-link calibration", "Sorting-effect measurement"], 1,
      "External equity benchmarks vs the labor market."),
    Q("A job-evaluation system that compares job worth across roles serves:",
      ["External equity assessment", "Internal equity assessment", "Pay-for-performance design", "Cost-benefit calculation"], 1,
      "Internal equity = equal pay for similar-worth jobs."),
    Q("A factory installs a piece-rate scheme. Productivity rises 44%. Gerhart & Rynes argue most of the gain came from:",
      ["Higher effort from existing workers", "Self-selection of better workers", "Better tools and processes", "Lower wage costs overall"], 1,
      "Sorting effect > incentive effect in the famous glass-installation study."),
    Q("A consultant proposes an ESOP. This is which type of incentive plan?",
      ["Individual-level incentive", "Group / team incentive", "Organization-wide incentive", "Discretionary incentive"], 2,
      "ESOPs reward at firm level — everyone shares."),
    Q("A reward strategy includes recognition, security and learning alongside cash. This is closest to:",
      ["Direct compensation only", "Total Returns model", "Forced-distribution rating", "Sorting-effect mechanism"], 1,
      "Total Returns = transactional + relational/psychological."),
    Q("A merit increase, unlike an incentive bonus, has the property that it:",
      ["Is always paid in cash only", "Permanently lifts the base pay", "Is contingent on a one-off goal", "Must be announced in advance"], 1,
      "Merit = base lift, sticky; incentive = re-earned, variable."),
    Q("A firm shifts variable pay weight from individual sales bonuses to team gain-sharing. The behavioral target is:",
      ["Solo selling productivity", "Team cooperation and shared output", "Personal sorting outcomes", "Compensation cost reduction"], 1,
      "Group-level incentives are designed to elicit team behavior."),
    Q("A firm in a Coordinated Market Economy is more likely than its LME peer to feature:",
      ["Lower unionization across sectors", "More legislation and coordination", "Stack-ranking style appraisals", "Aggressive wage cuts in downturns"], 1,
      "CMEs (Germany, Nordics): high unionization, coordination, legislation."),
    Q("Comparing a US firm to a German firm, the VoC framework labels the US as:",
      ["Coordinated Market Economy", "Liberal Market Economy", "Centrally Planned Economy", "Developmental State Economy"], 1,
      "US = LME; Germany = CME."),
    Q("A firm benchmarks on WorldatWork's Total Rewards model. Which is NOT one of the buckets?",
      ["Compensation bucket", "Benefits bucket", "Performance / recognition bucket", "Stock-buyback policy bucket"], 3,
      "Five buckets: compensation, benefits, work-life, performance/recognition, development/career."),
    Q("A firm uses broad pay bands with long progressions inside each grade. This is:",
      ["Narrow-graded structure", "Broad-graded / broadbanding", "Job-family structure", "Skill-based pay structure"], 1,
      "Broadbanding = few, wide grades; fits flatter orgs."),
    Q("A firm pays distinct ranges per occupational family (engineering vs marketing). This is:",
      ["Narrow-graded structure", "Broad-graded structure", "Job-family structure", "Skill-based pay structure"], 2,
      "Job-family = family-specific ranges."),
    Q("An employee receives flexitime, telecommuting and on-site childcare. These are:",
      ["Direct compensation", "Indirect monetary benefits", "Indirect non-monetary benefits", "Long-term incentive plans"], 2,
      "Non-monetary benefits enabling work-life integration."),
    Q("A firm offers paid health insurance plus pension contributions. These are:",
      ["Direct compensation items", "Indirect monetary benefits", "Indirect non-monetary benefits", "Long-term incentive plans"], 1,
      "Indirect monetary = cash-equivalent benefits."),
    Q("Per the Likelihood-to-Unionize Matrix, which group is MOST likely to unionize?",
      ["Self-employed contractors", "Gig and temporary workers", "White-collar professionals", "Blue-collar and public-sector"], 3,
      "High benefit + high ability → blue-collar + public sector."),
    Q("A consultancy claims a new incentive plan caused a productivity gain. Caveat Emptor asks FIRST:",
      ["Is the plan cheap to implement?", "Are there alternative explanations?", "Did unions oppose the plan?", "Is the plan Six-Sigma certified?"], 1,
      "Three questions: useful? correlation vs causation? alternative explanations?"),
    Q("A firm wants to attract high-output applicants and discourage low-output ones via pay design. They are using:",
      ["The incentive effect", "The sorting effect", "Internal equity design", "Total returns approach"], 1,
      "Sorting = self-selection through pay structure."),
    Q("Turnover spiked after wages slipped 12% below the industry median. The diagnosis is:",
      ["Internal equity violation", "External equity violation", "Sorting effect failure", "Pay-for-performance failure"], 1,
      "External equity gap drives turnover and attraction failures."),
    Q("The Pay Model's four objectives are:",
      ["Efficiency / Fairness / Ethics / Compliance", "Recruit / Retain / Reward / Recognize", "Internal / External / Performance / Cost", "Base / Variable / Benefits / Equity"], 0,
      "Objectives layer = EFEC. Option C is the four POLICY CHOICES — easy distractor swap."),
    Q("A pay system with consistent grade evaluation and survey benchmarking serves which Pay Model objective most directly?",
      ["Ethics objective", "Compliance objective", "Efficiency objective", "Fairness objective"], 3,
      "Internal + external equity → fairness."),
    Q("A firm in legal trouble over equal-pay claims has the weakest performance on which Pay Model objective?",
      ["Efficiency objective", "Compliance objective", "Ethics objective", "Fairness objective"], 1,
      "Compliance gap (statutory equal-pay obligations); fairness is related but compliance is the direct lever."),
    Q("A short-term incentive payable only when both individual AND firm targets are met combines:",
      ["Individual and organization-wide levers", "Direct and indirect compensation", "Sorting and incentive effects", "Internal and external equity"], 0,
      "Mixed level — individual + org goals."),
    Q("A firm's pay design predominantly attracts risk-averse, security-seeking employees. This is most consistent with:",
      ["Heavy variable / incentive pay mix", "Heavy base and benefits, low variable", "Wide broadbanding pay structure", "ESOP-heavy compensation mix"], 1,
      "Pay mix sorts for risk preference (incentive-heavy attracts risk-takers)."),
    Q("A firm shifts more of total comp from base pay to variable bonuses. Per Gerhart & Rynes the workforce will:",
      ["Stay the same in composition overall", "Sort toward risk-tolerant high performers", "Become more diverse on personality traits", "Demonstrate more continuance commitment"], 1,
      "Sorting effect — pay design changes who joins and stays."),
    Q("A narrow-graded pay structure is best suited to:",
      ["Flat, fluid organizations", "Hierarchical orgs with many steps", "Pure piece-rate workforces", "Fully variable pay schemes"], 1,
      "Many grades + step progressions match hierarchical orgs."),
    Q("A coordinated market economy is more likely to feature:",
      ["Hire-and-fire flexible labor markets", "Institutional coordination on training", "Right-to-work statutes across sectors", "Performance-ranked promotion logic"], 1,
      "CMEs coordinate via institutions; LMEs leave it to the market."),
    Q("A finance director claims the new bonus plan 'obviously caused' the revenue uplift this quarter. A Block-5 critique would:",
      ["Trust the consulting firm fully", "Test for alternatives and selection effects", "Increase the bonus next quarter", "Switch to Management by Objectives"], 1,
      "Caveat Emptor critique — correlation ≠ causation."),
    Q("'Useful?', 'Correlation vs causation?', 'Alternative explanations?' is which framework?",
      ["Caveat Emptor / Informed Consumer", "Pay Model's four objectives", "Four Criteria of Competitive Comp", "WorldatWork Total Rewards model"], 0,
      "Three-question critical appraisal model."),
    Q("'Internal alignment + external competitiveness + employee contributions + management' are:",
      ["Pay Model objectives", "Pay Model policy choices", "Four criteria of comp", "Total returns components"], 1,
      "The four POLICY CHOICES (vs the four objectives = EFEC)."),
]

BLOCK_6 = [
    Q("A CFO worries unionization will reduce profits via higher wages. Pfeffer would respond that:",
      ["Profits always fall under unions", "Higher wages often boost productivity", "Unions never raise wages anyway", "Profit effects are unrelated to unions"], 1,
      "Pfeffer: wage-profit link is mediated by productivity gains (feedback effects)."),
    Q("A firm in a competitive industry without monopoly power unionizes. Per Pfeffer the profit effect is likely:",
      ["Catastrophic and immediate", "Modest; large hit needs monopoly power", "Strongly positive in all cases", "Identical to non-union peers"], 1,
      "Pfeffer notes union profit hits bite mainly where firms hold market power to extract rents."),
    Q("A CEO claims unions kill HPWS. Pfeffer's contrary evidence comes from cases such as:",
      ["Walmart and McDonald's stores", "Ford, Saturn, Kaiser-Permanente", "Amazon, Starbucks and Tesla", "Goldman Sachs and JP Morgan"], 1,
      "Pfeffer's flagship cases of union + HPWS coexistence/synergy."),
    Q("Pfeffer's 'high road' competitive strategy means competing on:",
      ["The lowest labor costs possible", "Innovation, productivity, brainpower", "Government subsidies and grants", "Tariff protection and lobbying"], 1,
      "High road = innovation/productivity via HPWS; low road (cost) is unwinnable for advanced economies."),
    Q("A CEO insists 'good HR makes unions unnecessary'. This claim is:",
      ["Pfeffer's main thesis directly", "The conventional view Pfeffer rejects", "The Harvard Model in summary", "The Michigan Model in summary"], 1,
      "'Management gets the union it deserves' — Pfeffer disagrees with it."),
    Q("A unionized nursing setting outperforms non-union peers on patient mortality. Pfeffer attributes this to:",
      ["Higher staffing levels alone explain it", "Power-sharing and joint decision-making", "Lower nurse turnover effect alone", "Strict government regulation effects"], 1,
      "Power-sharing and joint problem-solving improve outcomes."),
    Q("A firm's wage dispersion is wide and performance is suffering. Pfeffer might suggest:",
      ["Wider wage dispersion further", "Wage compression (unions do this)", "Eliminating all base pay", "Moving to pure piece-rate"], 1,
      "Unions compress wage structures via their egalitarian ethos; wide dispersion harms performance."),
    Q("A bargaining committee reaches a tentative deal. It takes effect only after:",
      ["The CEO signs the agreement", "The business agent signs it", "Majority member ratification vote", "External mediator approval"], 2,
      "Ratification by member majority vote is required."),
    Q("A Tepperman's tentative deal is rejected 23-4 by members. The most likely next step is:",
      ["The deal takes effect anyway", "Return to bargaining or strike", "Immediate litigation in court", "Replacement of the union"], 1,
      "Rejected ratification → back to the table (or strike)."),
    Q("Kaiser-Permanente is cited by Pfeffer as evidence that:",
      ["Unions can deliver joint gains", "Unions raise patient mortality", "Adversarial bargaining is best", "Unions only work in factories"], 0,
      "K-P = cooperative partnership outperforming adversarial models."),
    Q("A union contract locks in training, teams, and job security. Pfeffer argues this:",
      ["Increases backsliding risk over time", "Reduces backsliding and entrenches HPWS", "Is irrelevant to HPWS adoption", "Always reduces investment levels"], 1,
      "Contract language prevents reversal of high-commitment practices."),
    Q("A US LME firm seeks the high road. Pfeffer argues union presence:",
      ["Forecloses the high road choice", "Makes high road more likely and durable", "Is neutral to strategic choice", "Only matters in CMEs not LMEs"], 1,
      "Unions can entrench HPWS that support the high road."),
    Q("A negotiating team enters with positions far apart. Effective bargaining tends to:",
      ["Pretend the differences do not exist", "Institutionalize joint problem-solving", "Eliminate the business-agent role entirely", "Avoid the ratification step entirely"], 1,
      "Pfeffer frames bargaining as power-sharing communication."),
    Q("A unionized retail chain shows lower turnover than non-union peers. Pfeffer would attribute this in part to:",
      ["Higher wages and reduced quitting", "Pure compensation arbitrage", "Reduced training investment", "Higher rates of layoff use"], 0,
      "Higher wages → lower turnover, a feedback effect that supports productivity."),
    Q("A government considers wage policy. Pfeffer's analysis suggests unions:",
      ["Can reduce wage inequality and discrimination", "Always worsen wage inequality", "Have no effect on inequality at all", "Only affect public-sector inequality"], 0,
      "Egalitarian ethos compresses dispersion across race and gender."),
    Q("An adversarial labor-management relationship tends to:",
      ["Maximize joint mutual gains", "Shrink gains both sides could share", "Improve ratification rates over time", "Eliminate the strike option entirely"], 1,
      "Cooperative > adversarial in delivering joint gains per Pfeffer."),
    Q("'Management gets the union it deserves' implies that:",
      ["Unionization is driven by management quality", "Pay levels alone determine unionization", "Industry composition determines unions", "Unions choose firms randomly to organize"], 0,
      "It frames unionization as a management failure (Pfeffer disagrees)."),
    Q("A unionized firm shifts to teamwork + decentralized decisions. Pfeffer suggests this works best when:",
      ["Implemented without union input at all", "Negotiated with the union and locked in contract", "Imposed unilaterally by management fiat", "Tied only to executive bonus targets"], 1,
      "Union endorsement + contract = durable HPWS."),
    Q("A non-union US tech firm pursues HPWS. Per Pfeffer the risk is:",
      ["HPWS will become impossible to run", "HPWS may erode under cost pressure", "HPWS will accelerate beyond limits", "HPWS will trigger instant unionization"], 1,
      "Without unions, contract-locked HPWS is harder to sustain when costs are squeezed."),
    Q("A union's egalitarian ethos affects pay structures by:",
      ["Compressing the wage distribution", "Widening the wage distribution", "Eliminating all piece-rate pay", "Eliminating all profit-sharing"], 0,
      "Solidarity requires more equal pay outcomes."),
    Q("Saturn (GM) is cited by Pfeffer because:",
      ["It failed entirely as a business", "It illustrates union + HPWS cooperation", "It only used Michigan-model PM", "It was non-union from the start"], 1,
      "Saturn is a Pfeffer case for union-management partnership and HPWS."),
    Q("The Tepperman's vote of 23-4 against the tentative deal indicates:",
      ["Strong member support for the deal", "Member dissatisfaction blocked the deal", "Management's preferred outcome", "A clear legal violation occurred"], 1,
      "23 against, 4 for: clear rejection."),
    Q("A negotiator argues 'we should never share information, it's leverage'. Pfeffer's view says:",
      ["Agreed — information is leverage", "Sharing is integral to joint problem-solving", "Information should only flow upward", "Information sharing has no effect"], 1,
      "Pfeffer frames bargaining as communication + joint decision-making."),
    Q("A unionized firm faces a cost crisis. Per Pfeffer the LEAST useful response is:",
      ["Joint problem-solving with the union", "Information sharing and shared sacrifice", "Adversarial wage cuts and confrontation", "Long-term productivity investment"], 2,
      "Adversarial moves shrink joint gains and break trust."),
    Q("A new HR director argues unions and HPWS are 'incompatible'. Pfeffer's evidence base says:",
      ["They are negatively correlated overall", "Positively associated; unions sustain HPWS", "They are entirely unrelated empirically", "HPWS only succeeds in non-union firms"], 1,
      "Positive association + durability via contract."),
    Q("A union wage settlement is followed by capital investment that raises labor productivity. This is:",
      ["A pure cost burden on the firm", "A feedback effect offsetting wage cost", "A sorting effect from the literature", "A rating error in HR appraisal"], 1,
      "Feedback effect: higher wages push firms to economize on labor via capital → productivity rises."),
    Q("A senior manager wants to predict where unionization will rise next. The Likelihood-to-Unionize Matrix focuses on:",
      ["Self-employed and remote workers", "Blue-collar and public-sector groups", "Senior executives and partners", "Independent contractors only"], 1,
      "High benefit + high ability → blue-collar + public sector."),
    Q("A firm narrows its labor strategy to low road (cost-cutting) vs high road (innovation). Pfeffer recommends:",
      ["Low road in all advanced economies", "High road, ideally union-backed", "Outsourcing all labor offshore", "Pure variable pay schemes only"], 1,
      "Low road is unwinnable vs developing economies."),
    Q("A bargaining process that excludes joint decision-making and treats labor as an adversary will:",
      ["Maximize joint value for both sides", "Limit gains and increase conflict", "Increase ratification rates always", "Reduce turnover automatically"], 1,
      "Adversarial bargaining reduces the size of the pie per Pfeffer."),
    Q("A union's biggest contribution to the high road, per Pfeffer, is:",
      ["Imposing legal protection alone", "Locking HPWS in via contracts and governance", "Reducing wage levels firm-wide", "Eliminating the strike threat itself"], 1,
      "Contract + governance entrenches the high-road strategic choice."),
]

DATA = {
    "subject": "People Management",
    "subjectId": "people_management",
    "blocks": [
        {"id": "b1", "title": "Block 1 — Foundations: SHRM, engagement & commitment", "questions": BLOCK_1},
        {"id": "b2", "title": "Block 2 — Job design, analysis, workforce planning & selection", "questions": BLOCK_2},
        {"id": "b3", "title": "Block 3 — Recruitment, selection, socialization, training", "questions": BLOCK_3},
        {"id": "b4", "title": "Block 4 — Performance management & appraisal", "questions": BLOCK_4},
        {"id": "b5", "title": "Block 5 — Compensation, incentives & employment relations", "questions": BLOCK_5},
        {"id": "b6", "title": "Block 6 — Unions, collective bargaining & labor relations", "questions": BLOCK_6},
    ],
}


def audit(data) -> list[str]:
    """Return list of warnings for questions whose correct option is suspiciously long."""
    warnings = []
    total = 0
    for b in data["blocks"]:
        for i, q in enumerate(b["questions"]):
            total += 1
            opts = q["options"]
            assert len(opts) == 4, f"{b['id']}#{i}: must have 4 options"
            assert 0 <= q["answer"] < 4, f"{b['id']}#{i}: bad answer index"
            correct_len = len(opts[q["answer"]])
            distractor_lens = [len(o) for j, o in enumerate(opts) if j != q["answer"]]
            longest_distractor = max(distractor_lens)
            shortest_distractor = min(distractor_lens)
            if correct_len - longest_distractor > LENGTH_TOLERANCE:
                warnings.append(
                    f"  ⚠ {b['id']} Q{i+1}: correct is {correct_len} chars, "
                    f"longest distractor is {longest_distractor}  ({correct_len - longest_distractor} over) — "
                    f"'{q['q'][:60]}…'"
                )
            elif correct_len < shortest_distractor - LENGTH_TOLERANCE:
                # also flag if correct is the SHORTEST by a wide margin (different leak)
                warnings.append(
                    f"  ⚠ {b['id']} Q{i+1}: correct is {correct_len} chars, "
                    f"shortest distractor is {shortest_distractor}  ({shortest_distractor - correct_len} under) — "
                    f"'{q['q'][:60]}…'"
                )
    print(f"Audited {total} questions across {len(data['blocks'])} blocks.")
    return warnings


def inject(html_path: Path, data: dict) -> None:
    html = html_path.read_text(encoding="utf-8")
    new_json = json.dumps(data, indent=2, ensure_ascii=False)
    pat = re.compile(
        r'(<script id="quiz-data" type="application/json">)(.*?)(</script>)',
        re.DOTALL,
    )
    if not pat.search(html):
        sys.exit("ERROR: <script id=\"quiz-data\"> block not found in HTML.")
    new_html = pat.sub(
        lambda m: m.group(1) + "\n" + new_json + "\n" + m.group(3),
        html,
        count=1,
    )
    html_path.write_text(new_html, encoding="utf-8")
    print(f"Injected {sum(len(b['questions']) for b in data['blocks'])} questions into {html_path.name}")


if __name__ == "__main__":
    warns = audit(DATA)
    if warns:
        print(f"\n{len(warns)} length-parity warnings (tolerance: ±{LENGTH_TOLERANCE} chars):")
        for w in warns:
            print(w)
    else:
        print("All options pass length-parity check ✓")
    inject(HTML, DATA)
